### ISSUE TITLE
When changing project phase, the current month is used for transition months

### ISSUE THREAD

**Issue by pwright08** [KainosSoftwareLtd/project-dashboard#45]
I updated a project on the alpha site from Alpha to Beta phase today (January 2017), but we actually started Beta in (I think) October 2016.

The end of Alpha and start of Beta months were set to January 2017.

Perhaps there should be a way to specify the month for cases where projects are not updated in the dashboard in the same month that they change phases.

**Comment by Rory80Hz** [comment]
Agree, being able to manage phases better would be an improvement.

**Comment by Rory80Hz** [comment]
As a Project Team Member in order to make sure the project timeline is correctly displayed I want to be able to decide the dates for each phase.

For the above, let's avoid confusion about where and when you can make changes, capture initial state on create, for edit and update we should use a specific journey to do this, and avoid over complicating the project details journey.

**Given** A new project is created
**When** specifying the phase
**Then** it is possible to specify the Month and Year it started

**Given** A Project is being edited
**When** details are entered
**Then** project phase is not part of the captured fields.

**Given** A users wants to edit or update project phases
**When** they navigate to a new Project Phases management UI
**Then** they have the ability to do so for all phases.
